# Generated by Django 5.0 on 2024-02-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0003_productcategory_alter_customuser_user_type_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembers',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
