# Generated by Django 5.0 on 2024-02-03 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0004_usermembers_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxapp.usermembers')),
                ('user_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxapp.product')),
            ],
        ),
    ]
