# Generated by Django 5.0 on 2024-02-03 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0006_alter_cart_user_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olxapp.usermembers'),
        ),
    ]
