# Generated by Django 5.0 on 2024-02-03 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0007_alter_cart_user_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.CharField(max_length=16)),
                ('shipping_address', models.TextField()),
                ('cvv', models.CharField(max_length=4)),
                ('user_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olxapp.usermembers')),
            ],
        ),
    ]
