# Generated by Django 5.0 on 2024-02-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0012_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
