# Generated by Django 5.0 on 2024-02-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0014_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_member',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
