# Generated by Django 5.0 on 2024-02-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0018_product_sold_alter_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
    ]
