# Generated by Django 5.0 on 2024-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0025_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
