# Generated by Django 5.0 on 2024-02-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0030_cartitem_status_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
