# Generated by Django 5.0 on 2024-02-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0036_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
