# Generated by Django 5.0 on 2024-02-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0040_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
