# Generated by Django 5.0 on 2024-02-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0045_usermembers_first_name_usermembers_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
