# Generated by Django 5.0 on 2024-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0050_remove_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.IntegerField(null=True),
        ),
    ]
