# Generated by Django 5.0 on 2024-02-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0051_order_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_id',
        ),
    ]
