# Generated by Django 5.0 on 2024-02-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0054_alter_order_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.IntegerField(null=True),
        ),
    ]
