# Generated by Django 5.0 on 2024-02-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0055_alter_order_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_id',
        ),
    ]
