# Generated by Django 5.0 on 2024-02-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0058_cart_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_id',
        ),
    ]
