# Generated by Django 5.0 on 2024-02-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0059_remove_order_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
