# Generated by Django 5.0 on 2024-02-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0061_remove_order_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
