# Generated by Django 5.0 on 2024-02-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0063_remove_order_seller_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
