# Generated by Django 5.0 on 2024-02-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0065_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.IntegerField(null=True),
        ),
    ]
