# Generated by Django 5.0 on 2024-02-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0067_remove_order_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
