# Generated by Django 5.0 on 2024-02-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0068_product_seller_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_username',
        ),
    ]
