# Generated by Django 5.0 on 2024-02-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0069_remove_product_seller_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
