# Generated by Django 5.0 on 2024-02-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0071_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
