# Generated by Django 5.0 on 2024-02-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0072_delete_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
