# Generated by Django 5.0 on 2024-02-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0074_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
