# Generated by Django 5.0 on 2024-02-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0076_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_name',
        ),
    ]
