# Generated by Django 5.0 on 2024-02-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0079_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
