# Generated by Django 5.0 on 2024-02-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0081_cart_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
