# Generated by Django 5.0 on 2024-02-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxapp', '0082_order_seller_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
